enum ActionConstant {
  GARAGE_PAGE = 'GARAGE_PAGE',
  GARAGE_CARS = 'GARAGE_CARS',
  WINNER_PAGE = 'WINNER_PAGE',
  WINNER_CARS = 'WINNER_CARS',
  WINNER_TOTAL_COUNT = 'WINNER_TOTAL_COUNT',
  WINNER_RESULT = 'WINNER_RESULT',
  CLEAN_WINNER_RESULT = 'CLEAN_WINNER_RESULT',
  LAST_TIME_WINNER = 'LAST_TIME_WINNER',
  SET_SORTING_OPTION = 'SET_SORTING_OPTION',
}
export const WINNER = 'WINNER';
export const GARAGE = 'GARAGE';

export default ActionConstant;