enum ActionConstant {
  GARAGE_PAGE = 'GARAGE_PAGE',
  GARAGE_CARS = 'GARAGE_CARS',
  WINNER_PAGE = 'WINNER_PAGE',
  WINNER_CARS = 'WINNER_CARS',
  WINNER_ID = 'WINNER_ID',
  LAST_TIME_WINNER = 'LAST_TIME_WINNER',
}

export default ActionConstant;